blueprint:
  name: Advanced Bathroom Occupancy with Voice Query
  description: "Manages a bathroom light using motion and door sensors. When the room appears to be empty (door closes and motion stops), it asks a question on a media player to confirm occupancy before turning off the light. Requires a configured Voice Assistant and an input_boolean helper."
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The sensor that detects motion in the bathroom.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    door_sensor:
      name: Door Sensor
      description: The sensor on the bathroom door.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    light_target:
      name: Light
      description: The light switch or light group to control.
      selector:
        target:
          entity:
            - domain: light
            - domain: switch
    occupancy_helper:
      name: Occupancy Helper (Input Boolean)
      description: An input_boolean helper to track if the room is occupied. This blueprint will manage its state.
      selector:
        entity:
          domain: input_boolean
    media_player:
      name: Media Player
      description: The speaker for asking the confirmation question.
      selector:
        entity:
          domain: media_player
    first_question_timeout:
      name: First Question Timeout (Seconds)
      description: Time to wait for response to the first occupancy question.
      selector:
        number:
          min: 30
          max: 180
          unit_of_measurement: seconds
          mode: slider
          step: 15
      default: 60
    second_question_timeout:
      name: Second Question Timeout (Seconds)
      description: Time to wait for response to the second (final) occupancy question.
      selector:
        number:
          min: 30
          max: 180
          unit_of_measurement: seconds
          mode: slider
          step: 15
      default: 90
    motion_clear_delay:
      name: Motion Clear Delay (Seconds)
      description: How long to wait after motion stops before checking occupancy.
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: seconds
          mode: slider
          step: 5
      default: 30
    manual_override_delay:
      name: Manual Override Delay (Seconds)
      description: How long to wait before checking sensors after manual light operation.
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: seconds
          mode: slider
          step: 5
      default: 10
    enable_manual_safeguards:
      name: Enable Manual Operation Safeguards
      description: When enabled, the automation will handle manual light operations intelligently.
      selector:
        boolean:
      default: true

    voice_assistant:
      name: Voice Assistant
      description: The voice assistant to use for speech recognition.
      selector:
        entity:
          domain: conversation
      default: conversation.home_assistant
    
    voice_query_script:
      name: Voice Query Script
      description: The script created from the 'Bathroom Occupancy Voice Query Script' blueprint.
      selector:
        entity:
          domain: script
          
mode: single

max_exceeded: silent

variables:
  motion_delay: !input motion_clear_delay
  manual_delay: !input manual_override_delay
  safeguards_enabled: !input enable_manual_safeguards

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
    id: motion_on
  - platform: state
    entity_id: !input door_sensor
    to: 'on'
    id: door_opened
  - platform: state
    entity_id: !input door_sensor
    from: 'on'
    to: 'off'
    id: door_closed
  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    for:
      seconds: "{{ motion_delay }}"
    id: motion_cleared
  - platform: state
    entity_id: !input light_target
    to: 'on'
    id: manual_light_on
  - platform: state
    entity_id: !input light_target
    to: 'off'
    id: manual_light_off

action:
  - choose:
      # === OCCUPANCY DETECTED ===
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: door_opened
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input occupancy_helper
          - service: homeassistant.turn_on
            target: !input light_target

      # === POTENTIAL EXIT DETECTED ===
      - conditions:
          - condition: trigger
            id: door_closed
          - condition: state
            entity_id: !input occupancy_helper
            state: 'on'
        sequence:
          - delay: '00:00:05'
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input motion_sensor
                    state: 'on'
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensor
                        to: 'off'
                        for:
                          seconds: "{{ motion_delay }}"
                    timeout: '00:05:00'
                    continue_on_timeout: false
                  - service: !input voice_query_script
                    data:
                      variables:
                        media_player_entity: !input media_player
                        occupancy_helper_entity: !input occupancy_helper
                        light_target_entity: !input light_target
                        first_question: "Is someone still in the bathroom? Please say yes or no."
                        second_question: "Last chance - is anyone still in the bathroom? Please say yes or no, or I will turn off the light."
                        first_timeout: !input first_question_timeout
                        second_timeout: !input second_question_timeout
                        turn_on_message: "Okay, keeping the light on."
                        turn_off_message: "Turning off the bathroom light."
            default:
              - service: !input voice_query_script
                data:
                  variables:
                    media_player_entity: !input media_player
                    occupancy_helper_entity: !input occupancy_helper
                    light_target_entity: !input light_target
                    first_question: "Is someone still in the bathroom? Please say yes or no."
                    second_question: "Last chance - is anyone still in the bathroom? Please say yes or no, or I will turn off the light."
                    first_timeout: !input first_question_timeout
                    second_timeout: !input second_question_timeout
                    turn_on_message: "Okay, keeping the light on."
                    turn_off_message: "Turning off the bathroom light."

      # === MANUAL LIGHT TURNED ON ===
      - conditions:
          - condition: trigger
            id: manual_light_on
          - condition: template
            value_template: "{{ safeguards_enabled }}"
        sequence:
          - delay:
              seconds: "{{ manual_delay }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input occupancy_helper
                    state: 'off'
                sequence:
                  - choose:
                      - conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input motion_sensor
                                state: 'on'
                              - condition: state
                                entity_id: !input door_sensor
                                state: 'on'
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: !input occupancy_helper
                    default:
                      - service: input_boolean.turn_on
                        target:
                          entity_id: !input occupancy_helper

      # === MANUAL LIGHT TURNED OFF ===
      - conditions:
          - condition: trigger
            id: manual_light_off
          - condition: template
            value_template: "{{ safeguards_enabled }}"
        sequence:
          - delay:
              seconds: "{{ manual_delay }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input occupancy_helper
                    state: 'on'
                sequence:
                  - choose:
                      - conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input motion_sensor
                                state: 'on'
                              - condition: state
                                entity_id: !input door_sensor
                                state: 'on'
                        sequence:
                          - service: !input voice_query_script
                            data:
                              variables:
                                media_player_entity: !input media_player
                                occupancy_helper_entity: !input occupancy_helper
                                light_target_entity: !input light_target
                                first_question: "Light was turned off manually. Should I turn it back on?"
                                second_question: "I'll keep the light off if I don't hear a response."
                                first_timeout: 60
                                second_timeout: 90
                                turn_on_message: "Turning the light back on."
                                turn_off_message: "Okay, keeping the light off."
                    default:
                      - service: input_boolean.turn_off
                        target:
                          entity_id: !input occupancy_helper

      # === MOTION CLEARED (Alternative trigger) ===
      - conditions:
          - condition: trigger
            id: motion_cleared
          - condition: state
            entity_id: !input occupancy_helper
            state: 'on'
          - condition: state
            entity_id: !input door_sensor
            state: 'off'
        sequence:
          - service: !input voice_query_script
            data:
              variables:
                media_player_entity: !input media_player
                occupancy_helper_entity: !input occupancy_helper
                light_target_entity: !input light_target
                first_question: "Is someone still in the bathroom? Please say yes or no."
                second_question: "Last chance - is anyone still in the bathroom? Please say yes or no, or I will turn off the light."
                first_timeout: !input first_question_timeout
                second_timeout: !input second_question_timeout
                turn_on_message: "Okay, keeping the light on."
                turn_off_message: "Turning off the bathroom light."
